=== Dangal-Santosh/XML-Project/catalog_19031638.dtd
<?xml encoding="UTF-8"?>
<!--Root Element-->
<!ELEMENT Store (Store_Name,Address,Telephone_Number,Email_Address,Website_Address,Logo,Welcome,Music,Copyright)>
<!--<!ATTLIST Store
 xmlns:xsi CDATA #FIXED 'http://www.w3.org/2001/XMLSchema-instance'
 xsi:noNamespaceSchemaLocation CDATA #REQUIRED>-->
 <!--Store_Name Element -->
<!ELEMENT Store_Name (#PCDATA)>
<!--Address Element -->
<!ELEMENT Address (#PCDATA)>
<!--Telephone_Number Element -->
<!ELEMENT Telephone_Number (#PCDATA)>
<!--Email_Address Element -->
<!ELEMENT Email_Address (#PCDATA)>
<!-- Website_Address Element -->
<!ELEMENT Website_Address (#PCDATA)>
<!-- Logo Element -->
<!ELEMENT Logo EMPTY>
<!-- Defining attribute type of Logo -->
<!ATTLIST Logo image CDATA "img">
<!ELEMENT Welcome (#PCDATA)>
<!ELEMENT Music (Album+)>
<!ELEMENT Copyright (#PCDATA)>
<!ELEMENT Album (Song+)>
<!-- Defining attribute type of Album -->
<!ATTLIST Album id ID #REQUIRED>
<!ELEMENT Song (Information,Banner,Description+)>
<!-- Defining attribute type of Song -->
<!ATTLIST Song Song_no CDATA #REQUIRED>
<!ATTLIST Song Song_label CDATA #REQUIRED>
<!ELEMENT Information (#PCDATA)>
<!ELEMENT Banner (#PCDATA)>
<!-- Defining attribute type of Banner -->
<!ATTLIST Banner id ID #REQUIRED>
<!ELEMENT Description (Song_Name,Song_Length,Released_Year,Genre,Video_Making+,Producer,Nationality,Language,Song_Writer,Singer,IMDb_Rating,(Awards|Certification|Concert|Performance|Billboard|Studio)?)>
<!ELEMENT Song_Name (#PCDATA)>
<!ELEMENT Song_Length (#PCDATA)>
<!ELEMENT Released_Year (#PCDATA)>
<!ATTLIST Released_Year date CDATA #REQUIRED>
<!ELEMENT Genre (#PCDATA)>
<!ELEMENT Video_Making (Director,Location,Actor,Views)>
<!ELEMENT Director (#PCDATA)>
<!ELEMENT Location (#PCDATA)>
<!ELEMENT Actor (#PCDATA)>
<!ELEMENT Views (#PCDATA)>
<!-- Defining attribute type of Views -->
<!ATTLIST Video_Making type CDATA #REQUIRED>
<!ELEMENT Producer (#PCDATA)>
<!ELEMENT Nationality (#PCDATA)>
<!ELEMENT Language (#PCDATA)>
<!ELEMENT Song_Writer (#PCDATA)>
<!ELEMENT Singer (#PCDATA)>
<!ELEMENT IMDb_Rating (#PCDATA)>
<!ELEMENT Performance (#PCDATA)>
<!ELEMENT Certification (#PCDATA)>
<!ELEMENT Awards (#PCDATA)>
<!ELEMENT Concert (#PCDATA)>
<!ELEMENT Billboard (#PCDATA)>
<!ELEMENT Studio (#PCDATA)>

=== Dangal-Santosh/XML-Project/catalog_19031638.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?> 
<!--   Author: Santosh Dangal 
 	   Date: 13th April, 2021  
--> 
<?xml-stylesheet href="catalog_19031638.css" type="text/css"?>
<!--<!DOCTYPE Store SYSTEM "catalog_19031638.dtd">-->
<!--Root Tag -->
<Store xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="catalog_19031638.xsd">
	<!-- Name of the Store -->
	<Store_Name>Dark Knight Music Zone</Store_Name>
	<!-- Address of the Store -->
	<Address>Durbarmarg, Kathmandu</Address>
	<!-- Contact Number of the Store -->
	<Telephone_Number>01-4757389</Telephone_Number>
	<!-- Email Address of the Store -->
	<Email_Address>Customer.care@DarkKnightMusic.com</Email_Address>
	<!-- Website Address of the Store -->
	<Website_Address>www.DarkKnightMusic.com</Website_Address>
	<!-- Logo of the Store -->
	<Logo image="img"/>
	<!-- Welcome Image for the website -->
	<Welcome></Welcome>
	<!-- Dark Knight Music -->
	<Music>
		<!-- Dark Knight Albums-->
	 	<Album id ="Origins">
	 		<!-- Dark Knight Song-->
	 		<Song Song_no="song_1" Song_label="Interscope; ‎Kidinakorner">
	 			<!-- Information of the Song -->
	 			<Information>
					<![CDATA["Bad Liar" is a song by American pop rock band Imagine Dragons. The song was released through Interscope and Kidinakorner records on November 6, 2018 as the fourth single from their fourth studio album, Origins (2018). It was written by Imagine Dragons, Aja Volkman and Jorgen Odegard, and produced by Odegard."Bad Liar" peaked at number 56 one the US Billboard Hot 100.]]>
				</Information>
				<!-- Banner of Song -->
				<Banner id="banner_001"/>
				<!-- Description of Song -->
				<Description>
					<Song_Name>Bad Liar</Song_Name>
					<Song_Length>4:20</Song_Length>
					<Released_Year date="A.D.">2018</Released_Year>
					<Genre>Electropop</Genre>
					<Video_Making type="string"> 
						<Director>Ryan Reichenfeld</Director>
						<Location>Green Valley High School, Henderson, Nevada</Location>
						<Actor>Autumn Miller</Actor>
						<Views>300 million on Youtube</Views>
					</Video_Making>
					<Producer>Jorgen Odegard</Producer>
					<Nationality>USA</Nationality>
					<Language>English</Language>
					<Song_Writer>Aja Volkman</Song_Writer>
					<Singer>Imagine Dragons</Singer>
					<IMDb_Rating>6.5</IMDb_Rating>
					<!--Optional element-->
					<Performance>Cosmopolitan in Las Vegas, Nevada,2019 National College Football Championship,USA</Performance>
									
				</Description>
			</Song>
			<Song Song_no="song_2" Song_label="	
			Kidinakorner;Interscope,Walt Disney">
	 			<!-- Information of the Song -->
				<Information>
					<![CDATA["Zero" is a song by American pop rock band Imagine Dragons, who co-wrote it with their producer John Hill. It is the second single from the band's fourth studio album Origins.The song is featured in the Disney animated film Ralph Breaks the Internet and was included in its second official trailer and its soundtrack.]]>
				</Information>
				<!-- Banner of Song -->
				<Banner id="banner_002"/>
				<!-- Description of Song -->
				<Description>
					<Song_Name>Zero</Song_Name>
					<Song_Length>3:30</Song_Length>
					<Released_Year date="A.D.">2018</Released_Year>
					<Genre>Pop rock</Genre>
					<Video_Making type="string"> 
						<Director>Rich Moore and Byron Howard</Director>
						<Location>Disney Films:Ralph Breaks the Internet</Location>
						<Actor>Dan Reynolds, Wayne Sermon, Ben McKee, Daniel Platzman</Actor>
						<Views>71 million on Youtube</Views>
					</Video_Making>
					<Producer>John Hill</Producer>
					<Nationality>All Countries</Nationality>
					<Language>English</Language>
					<Song_Writer>Dan Reynolds,Ben McKeeWayne, Sermon, Daniel Platzman, John Hill</Song_Writer>
					<Singer>Imagine Dragons</Singer>
					<IMDb_Rating>7</IMDb_Rating>

									
				</Description>
			</Song>
		</Album>
		
		<Album id ="Vida">
	 		<!-- Dark Knight Song-->
	 		<Song Song_no="song_3" Song_label="Universal Latin">
	 			<!-- Information of Song -->
				<Information>
					<![CDATA["Despacito" (American Spanish: [despa'sito]; transl. "Slowly") is a song by Puerto Rican singer Luis Fonsi featuring Puerto Rican rapper Daddy Yankee from Fonsi's 2019 studio album Vida. Released on January 12, 2017, the song was written by Fonsi, Erika Ender and Daddy Yankee, and produced by Mauricio Rengifo and Andrés Torres.]]>
				</Information>
				<!-- Banner of Song -->
				<Banner id="banner_003"/>
				<!-- Description of the Song -->
				<Description>
					<Song_Name>Despacito</Song_Name>
					<Song_Length>3:47</Song_Length>
					<Released_Year date="A.D.">2017</Released_Year>
					<Genre>Reggaeton, Latin pop</Genre>
					<Video_Making type="string"> 
						<Director>Carlos Pérez</Director>
						<Location>La Perla neighborhood and bar La Factoría in San Juan,Puerto Rico </Location>
						<Actor>Luis Fonsi, Daddy Yankee, Zuleyka Rivera</Actor>
						<Views>7.3 billion on Youtube</Views>
					</Video_Making>
					<Producer>Mauricio Rengifo Andrés Torres</Producer>
					<Nationality>Spain,USA</Nationality>
					<Language>Spanish English</Language>
					<Song_Writer>Luis Rodríguez, Erika Ender, Ramón Ayala(Spanish), Samper(English)</Song_Writer>
					<Singer>Luis Fonsi Daddy Yanke(Original), Justin Bieber(English) </Singer>
					<IMDb_Rating>6</IMDb_Rating>
									
				</Description>
			</Song>
			<Song Song_no="song_4" Song_label="Universal Latin eed Universal">
	 			<!-- Information of Song -->
				<Information>
					<![CDATA["Imposible" is a song by Puerto Rican singers Luis Fonsi and Ozuna, released on October 19, 2018, through Universal Music Latin Entertainment.[1] The song topped the charts in Chile and reached the top 10 in Argentina, Bolivia, Panama and Spain.]]>
				</Information>
				<!-- Banner of Song -->
				<Banner id="banner_004"/>
				<!-- Description of the Song -->
				<Description>
					<Song_Name>Impossible</Song_Name>
					<Song_Length>2:43</Song_Length>
					<Released_Year date="A.D.">2018</Released_Year>
					<Genre>Reggaeton Latin pop</Genre>
					<Video_Making type="string"> 
						<Director>Carlos Perez</Director>
						<Location>Miami,USA</Location>
						<Actor>Luis Fonsi Ozuna</Actor>
						<Views>423 million on Youtube</Views>
					</Video_Making>
					<Producer>Andrés Torres,Mauricio Rengifo</Producer>
					<Nationality>Spain</Nationality>
					<Language>Spanish</Language>
					<Song_Writer>Luis Fonsi,Vicente Saavedra, Mauricio Rengifo, Juan Carlos, Ozuna Rosado, Andrés Torres</Song_Writer>
					<Singer>Luis Fonsi Ozuna</Singer>
					<IMDb_Rating>6</IMDb_Rating>
									
				</Description>
			</Song>
		</Album>
		<Album id ="Rare">
	 		<!-- Dark Knight Song-->
	 		<Song Song_no="song_5" Song_label="Interscope">
	 			<!-- Information of the Song -->
				<Information>
					<![CDATA["Lose You to Love Me" is a song by American singer Selena Gomez, released by Interscope Records on October 23, 2019, as the lead single from Gomez's third studio album, Rare (2020). The song was written by Gomez, Julia Michaels, Justin Tranter, and its producers Mattman & Robin.]]>
				</Information>
				<!-- Banner of Song -->
				<Banner id="banner_005"/>
				<!-- Description of the Song -->
				<Description>
					<Song_Name>Lose You to Love Me</Song_Name>
					<Song_Length>3:26</Song_Length>
					<Released_Year date="A.D.">2019</Released_Year>
					<Genre>Pop</Genre>
					<Video_Making type="string"> 
						<Director>Sophie Muller</Director>
						<Location>Los Angeles,USA</Location>
						<Actor>Selena Gomez</Actor>
						<Views>606 million on Youtube</Views>
					</Video_Making>
					
					<Producer>Mattman and Robin</Producer>
					<Nationality>America</Nationality>
					<Language>English</Language>
					<Song_Writer>Selena Gomez, Julia Michaels, Justin Tranter, Mattias Larsson, Robin Fredriksson</Song_Writer>
					<Singer>Selena Gomez</Singer>
					<IMDb_Rating>7.6</IMDb_Rating>
					<!--Optional element-->
					<Certification>2x Platinum in Australia, Platinum in United Kingdom</Certification>
									
				</Description>
			</Song>
			<Song Song_no="song_6" Song_label="Interscope">
	 			<!-- Information of Song -->
				<Information>
					<![CDATA["Look at Her Now" is a song by American singer Selena Gomez. It was released on October 24, 2019, by Interscope Records as the second single from her third studio album Rare (2020), a day after "Lose You to Love Me". The song was written by Gomez, Julia Michaels, Justin Tranter and its producer Ian Kirkpatrick. It has been described as a dance-pop, electropop and synth-pop song.]]>
				</Information>
				<!-- Banner of Song -->
				<Banner id="banner_006"/>
				<!-- Description of Car -->
				<Description>
					<Song_Name>Look at Her Now</Song_Name>
					<Song_Length>2:42</Song_Length>
					<Released_Year date="A.D.">2019</Released_Year>
					<Genre>Dance-pop electropop synth-pop</Genre>
					<Video_Making type="string"> 
						<Director>Sophie Muller</Director>
						<Location>Los Angeles,USA</Location>
						<Actor>Selena Gomez</Actor>
						<Views>201 million on Youtube</Views>
					</Video_Making>
					<Producer>Ian Kirkpatrick</Producer>
					<Nationality>America</Nationality>
					<Language>English</Language>
					<Song_Writer>Selena Gomez, Julia Michaels, Justin Tranter, Ian Kirkpatrick
					</Song_Writer>
					<Singer>Selena Gomez</Singer>
					<IMDb_Rating>6.5</IMDb_Rating>
									
				</Description>
			</Song>
		</Album>
		<Album id ="Divide">
	 		<!-- Dark Knight Song-->
	 		<Song Song_no="song_7" Song_label="Asylum 
	 			Atlantic">
	 			<!-- Information of Song -->
				<Information>
					<![CDATA["Perfect" is a song by English singer-songwriter Ed Sheeran from his third studio album, ÷ (2017). After the album's release, it charted at number four on the UK Singles Chart. On 21 August 2017, Billboard announced that "Perfect" would be the fourth single from the album.]]>
				</Information>
				<!-- Banner of Song -->
				<Banner id="banner_007"/>
